version: '3'

tasks:
  build:
    cmds:
      - go build -v gremlins/cmd/logservice
      - go build -v gremlins/cmd/registryservice
      - go build -v gremlins/cmd/gremlin
      - go build -v gremlins/cmd/keeper

  clean:
    cmds:
      - rm logservice
      - rm registryservice
      - rm gremlin
      - rm keeper